trigger: none 

pool:
  name: todo-infra-agent-pool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
    backendServiceArm: 'sp-1'
    backendAzureRmStorageAccountName: 'teststa20234'
    backendAzureRmContainerName: 'statefile-container'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'sp-1'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
    environmentServiceNameAzureRM: 'sp-1'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
    environmentServiceNameAzureRM: 'sp-1'


