trigger:
  branches:
    include:
      - feature/*
      - main


pool:
  name: todo-infra-agent-pool

variables:
  working_path: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
  service_connection: 'sp-1'

steps:

- task: TerraformInstaller@1
  displayName: 'Terraform Installer'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(working_path)
    backendServiceArm: $(service_connection)
    backendAzureRmStorageAccountName: 'teststa20234'
    backendAzureRmContainerName: 'statefile-container'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform FMT'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    customCommand: 'fmt'
    workingDirectory: $(working_path)
    outputTo: 'console'
    environmentServiceNameAzureRM: $(service_connection)

- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(working_path)
    environmentServiceNameAzureRM: $(service_connection)

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(working_path)
    environmentServiceNameAzureRM: $(service_connection)

- task: TerraformTask@5
  displayName: 'Terraform Apply'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: $(working_path)
    environmentServiceNameAzureRM: $(service_connection)
