trigger: none
pool:
name: 'todo-infra-agent-pool'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    backendServiceArm: 'sp-1'
    backendAzureRmStorageAccountName: 'stadummy20234'
    backendAzureRmContainerName: 'statefile'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'