# ==============================
#  PIPELINE LEVEL
# ==============================

trigger:
  branches:
    include:
      - feature/*     # -> Feature branches auto-trigger

pool:
  name: todo-infra-agent-pool

variables:
  working_path: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
  service_connection: 'sp-1'


# ==============================
#  STEPS LEVEL
# ==============================

steps:

- task: TerraformInstaller@1
  displayName: 'Terraform Installer'
  inputs:
    terraformVersion: 'latest'


# ----------- INIT ------------
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(working_path)
    backendServiceArm: $(service_connection)
    backendAzureRmStorageAccountName: 'teststa20234'
    backendAzureRmContainerName: 'statefile-container'
    backendAzureRmKey: 'terraform.tfstate'


# ----------- FMT ------------
- task: TerraformTask@5
  displayName: 'Terraform FMT'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: $(working_path)
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: $(service_connection)


# ----------- VALIDATE ------------
- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(working_path)
    environmentServiceNameAzureRM: $(service_connection)


# ----------- PLAN ------------
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(working_path)
    environmentServiceNameAzureRM: $(service_connection)

# ----------- APPLY DISABLED ------------
- task: TerraformTask@5
  displayName: 'Terraform Apply - Disabled on Feature Branch'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
  enabled: false
