trigger: none 

pool: 
  name: todo-infra-agent-pool

steps:

- task: TerraformInstaller@1
  displayName: "install terraform"
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: string # Human-readable name for the task.
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
    backendServiceArm: 'sp-1'
    backendAzureRmStorageAccountName: 'dummy20233'
    backendAzureRmContainerName: 'statefile'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: "Terraform fmt"
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'sp-1'

- task: TerraformTask@5
  displayName: "Terraform Plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
    environmentServiceNameAzureRM: 'sp-1'
- task: TerraformTask@5
  displayName: "Terraform Apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Todo-infra-setup'
    environmentServiceNameAzureRM: 'sp-1'

